AWSTemplateFormatVersion: "2010-09-09"
Description: "Create AWS Resources"

Resources:
  
  WorkflowJob:
    Type: AWS::Glue::Workflow
    Properties:
      Description: Create workflow
      MaxConcurrentRuns: 1
      Name: jobworkflow

  GlueJobImport:
    Type: AWS::Glue::Job
    Properties:
      Name: data-ingestion1
      Description: Ingests data from s3 and writes it as a parquet file to the data lake
      ExecutionClass: FLEX
      GlueVersion: 4.0
      MaxRetries: 0
      NumberOfWorkers: 6
      Role: arn:aws:iam::948501703392:role/LabRole
      Timeout: 90
      WorkerType: G.1X
      Command:
        Name: glueetl
        ScriptLocation: s3://finalprojectinput/github/products/Products_Glue_Job.py
      DefaultArguments:
        "--job-bookmark-option": "job-bookmark-enable"

    
    WorkflowStartTrigger:
      Type: AWS::Glue::Trigger
      Properties:
      Name: StartTrigger
      Type: ON_DEMAND
      Description: Trigger for starting the workflow
      Actions:
        - JobName: !Ref GlueJobImport
      WorkflowName: !Ref WorkflowJob


      MyAthenaWorkGroup:
        Type: AWS::Athena::WorkGroup
        Properties:
            Name: gitworkgrp
            Description: workgroup for Athena
            State: ENABLED
            WorkGroupConfiguration:
                BytesScannedCutoffPerQuery: 200000000
                EnforceWorkGroupConfiguration: false
                PublishCloudWatchMetricsEnabled: true
                RequesterPaysEnabled: true
                ResultConfiguration:
                    OutputLocation: s3://group04output/Query/    
