AWSTemplateFormatVersion: "2010-09-09"
Description: "Create AWS Resources"

Resources:
  GlueJobSalesData:
    Type: AWS::Glue::Job
    Properties:
      Name: Sales_Glue_Job
      Description: Ingests data from s3 and after doing transformation it writes the data as a parquet file to the data warehouse
      ExecutionClass: FLEX
      GlueVersion: 4.0
      MaxRetries: 0
      NumberOfWorkers: 8
      Role: arn:aws:iam::948501703392:role/LabRole
      Timeout: 90
      WorkerType: G.1X
      Command:
        Name: glueetl
        ScriptLocation: s3://pract-buck/destination_file/salesjob/sales_gluejob.py
      DefaultArguments:
        "--job-bookmark-option": "job-bookmark-enable"

  GlueJobProductsData:
    Type: AWS::Glue::Job
    Properties:
      Name: Product_Glue_Job
      Description: Ingests data from RDS and after doing transformation it writes the data as a parquet file to the data warehouse
      ExecutionClass: FLEX
      GlueVersion: 4.0
      MaxRetries: 0
      NumberOfWorkers: 6
      Role: arn:aws:iam::948501703392:role/LabRole
      Timeout: 90
      WorkerType: G.1X
      Command:
        Name: glueetl
        ScriptLocation: s3://pract-buck/destination_file/productjob/products_gluejob.py
      DefaultArguments:
        "--job-bookmark-option": "job-bookmark-enable"

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Role: arn:aws:iam::948501703392:role/LambdaRole
      Code:
        S3Bucket: your-lambda-code-bucket
        S3Key: lambda_function.zip
      Runtime: python3.8
      Timeout: 60

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: flipkart-sales
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:*
            Function: !GetAtt LambdaFunction.Arn

  S3EventPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt LambdaFunction.Arn
      Principal: s3.amazonaws.com
      SourceAccount: !Ref "AWS::AccountId"
      SourceArn: !GetAtt S3Bucket.Arn
